name: shara
version: '0.1.0.0'
category: Solver
author: David Heath and Qi Zhou
maintainer: heath.davidanthony@gmail.com
license: MIT

default-extensions:
- LambdaCase
- MultiWayIf
- GeneralizedNewtypeDeriving
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- RankNTypes
- FlexibleContexts
- FlexibleInstances
- NoMonomorphismRestriction
- PatternSynonyms

dependencies:
- base
- ghc-paths
- temporary
- containers
- parsec
- parsec-numbers
- unordered-containers
- pretty
- array
- mtl
- monad-loops
- lens
- prettyprinter
- split
- template-haskell
- syb
- z3 >=4.1
- turtle
- extra
- async >=2.1
- stm
- QuickCheck
- hspec
- semiring-simple
- formal-language

library:
  ghc-options: -Wall
  source-dirs: src

  exposed-modules:

executable:
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
  main: Main.hs
  source-dirs: app
  dependencies:
    - shara
