name: shara
version: '0.1.0.0'
category: Solver
author: David Heath and Qi Zhou
maintainer: heath.davidanthony@gmail.com
license: MIT

default-extensions:
- LambdaCase
- MultiWayIf
- FlexibleContexts

dependencies:
- base
- containers
- mtl
- extra
- lens
- split
- async >=2.1
- formal-language
- formula
- prettyprinter

library:
  ghc-options: -Wall
  source-dirs: src

  exposed-modules:

executable:
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
  main: Main.hs
  source-dirs: app
  dependencies:
    - shara
