flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: f18110558d74dd8df8560f2b0fc2cc0704673917
  extra-dep: true
- location:
    git: https://github.com/DAHeath/formal-language
    commit: 87bec42b7df244471846153329cfe7a3cf50c450
  extra-dep: true
- location:
    git: https://github.com/DAHeath/formula
    commit: df11d60def711545c98113eef672f2a07d6c342e
  extra-dep: true
extra-deps:
- parsec-numbers-0.1.0
- prettyprinter-1.1.1
- global-lock-0.1
resolver: lts-11.4
